add vault wrapper script

diff --git a/hiera/hostbase.yaml b/hiera/hostbase.yaml
--- a/hiera/hostbase.yaml
+++ b/hiera/hostbase.yaml
@@ -75,6 +75,25 @@ ressources:
   file:
     "/srv":
       ensure: directory
+    "/usr/local/bin/mvault":
+      ensure: present
+      mode: "0755"
+      content: |
+        #!/usr/bin/env bash
+
+        VAULT_BIN=$(which vault)
+        export VAULT_ADDR=https://vault.srv.gentoomaniac.net/
+
+        # renew vault token:
+        if [ -n "${VAULT_BIN}" ]; then
+            VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$(cat /etc/vault_role_id)" secret_id="$(cat /etc/vault_secret_id)")
+            export VAULT_TOKEN
+        else
+            echo "Vault binary not found"
+            exit 1
+        fi
+
+        ${VAULT_BIN} "$@"
 
 docker::docker_users:
   - marco
